### ISSUE TITLE
esp32 i2c Errorcode:2

### ISSUE THREAD

**Issue by Chris-656** [hibit-dev/mpu9250#1]
I am using this lib with esp32 and i2c.
I get the error -> I2C ERROR CODE : 2

after the calibratio  is finished.
I also used internal pullups as a test but no change.
can u help
regards Chris

**Comment by tmekinyan** [comment]
Debugging can be challenging without access to the wiring diagram and code. In general, this issue indicates that the chips are either not properly connected or the wrong address was transmitted.

**Comment by Chris-656** [comment]
Thx I bought a wrong Chip, without magnet
Sorry
Brstcregards Chris
